### ISSUE TITLE
Background Image Changes

### ISSUE THREAD

**Issue by ambha21** [acm-uiowa/uigrades-old#11]
From page to page, the scale of the background image changes. I don't know if it is currently possible to keep the scale of the background image the same (from page to page) since the size of the page is dynamic.

**Comment by liaozhuzhu** [comment]
This is a feature i had in mind where the background image expands out the deeper you go into the site, almost like you're entering a tunnel. lmk what you think abt this.

**Comment by ambha21** [comment]
Sounds good. Hypothetically, is it even possible to execute my idea? I just wanted to know that because I was curious

**Comment by liaozhuzhu** [comment]
Yeah we can use just set the bg images to the images we have saved
